### ISSUE TITLE
Rename versions.json to dataset.json

### ISSUE THREAD

**Issue by tischi** [mobie-org/covid-em-datasets#1]
@constantinpape 
Rename versions.json to dataset.json
I'll do it by hand.

**Comment by constantinpape** [comment]
No, please wait

**Comment by constantinpape** [comment]
I have code to do all of this

**Comment by constantinpape** [comment]
I am about to do this right now

**Comment by tischi** [comment]
Yes, I just stopped while doing it, because of what you just answered.
:-)
