### ISSUE TITLE
Accessability without aws config

### ISSUE THREAD

**Issue by jhennies** [mobie-org/covid-em-datasets#11]
Hey @constantinpape,

Our collaborator was trying to access the FIB-SEM datasets and failed, while he was able to access the tomo data. 
I could reproduce by removing the aws credentials from my home, then the tomo stuff works but the FIB doesn't. 

I guess, we also want the FIB data public, do you know how to fix this?

Cheers,
Julian

**Comment by constantinpape** [comment]
Yes, I think the bucket is not publicly accessible.
We need to ask EMBL-IT to make it public.

I will make a ticket about it and cc you.

**Comment by jhennies** [comment]
Ok, great thanks!

**Comment by constantinpape** [comment]
Once the permissions are changed for the bucket, we also need to change the xmls from `Protected` to `Anonymous`.
E.g. here: https://github.com/mobie/covid-em-datasets/blob/master/data/Covid19-S5-mock-Cell1-2/images/remote/fibsem-raw.xml#L33

**Comment by constantinpape** [comment]
It should be accessible by anyone now.
Feel free to reopen if there are any more issues here, @jhennies.
