### ISSUE TITLE
Covid19-S5-mock-Cell1-2 is missing the xmls in git

### ISSUE THREAD

**Issue by constantinpape** [mobie-org/covid-em-datasets#6]
@martinschorb the new dataset `Covid19-S5-mock-Cell1-2` is missing the xmls in git, so it can't be opened right now when using the git address in `Open MoBIE Project`.

Just wanted to let you know in case you were not aware of this.

**Comment by martinschorb** [comment]
I pushed pretty much exactly when you noticed ;-)
